### ISSUE TITLE
File imports not working 

### ISSUE THREAD

**Issue by medorus** [chel-mico/CSBless#3]
Imports such as 
`const helper = require(path.join("/CSBless", "/helpers", "/matrices.js"));`
are resulting in a 'Module not found' error (Windows). An example fix would be something like this:
`const rootDir = path.dirname(require.main.filename);`
`const helper = require(path.join(rootDir, "helpers", "matrices.js"));`
However I am not sure how this will function on MacOS.

**Comment by chel-mico** [comment]
I've caught this myself already, an update addressing this and more is in the works. Check out main branch for a sample.

**Comment by chel-mico** [comment]
Update: a fix has been officially released.
